name: Build and deploy LaTeX document

on:
  push:
    branches:
      - rapport-src
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: rapport.tex
          working_directory : rapport/
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: annexe.tex
          working_directory : rapport/annexe/
      - name: Copy to public folder for deployment
        shell: bash
        run: |
          mkdir -p public
          cp rapport/rapport.pdf public/rapport.pdf
          cp rapport/annexe/annexe.pdf public/annexe.pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: rapport-out
          force_orphan: true # Ensures that not all previous PDFs are kept around forever

